socialtracking/main/routes.py
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint
from socialtracking.models import User, Post
from socialtracking.posts.forms import SearchBar
from flask_login import login_user, current_user, login_required

main = Blueprint('main', __name__)

@main.route('/homepage', methods=['GET', 'POST']) #The homepage where users can see all of the entries that they have created.
@login_required
def homepage():
    form = SearchBar() #Form that has the elements for the search bar
    if form.validate_on_submit(): #If the search bar button is clicked then:
        search = form.search_field.data #Get what the value in the text field is
        page = request.args.get('page', 1, type=int)
        posts = Post.query.filter_by(person_met = search, author=current_user).paginate(page=page, per_page=4)#Paginate the results of the filter with a max of 
        if posts == 0:   #Could not figure out how to work but the logic is there                             #4 posts per page.
            flash('There were no results', 'danger')
        page = request.args.get('page', 1, type=int)
        return render_template('homepage.html', posts=posts, form=form)
    else:
        page = request.args.get('page', 1, type=int) #If the search bar is not activated simply serve all of the entries created by the user
        posts = Post.query.filter_by(author=current_user).order_by(Post.date_met.desc()).paginate(page=page, per_page=4)
        return render_template('homepage.html', posts=posts, form=form)

socialtracking/posts/routes.py
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint, current_app
from socialtracking import db, bcrypt
from socialtracking.posts.forms import PostForm, SearchBar
from socialtracking.models import User, Post
from flask_login import login_user, current_user, logout_user, login_required

posts = Blueprint('posts', __name__)

def check_author_access(post):
    if post.author != current_user:             #make sure that only the owner can access the tracker, dont allow access to ther peoples trackers
        abort(403)
        return False

def add_to_database(post):
    db.session.add(post)
    db.session.commit()

def update_database(post, form):
    post.person_met = form.name_title.data
    post.content = form.content.data
    db.session.commit()

def fill_text_fields(post, form):
    form.name_title.data = post.person_met
    form.content.data = post.content

def delete_in_database(post):
    db.session.delete(post)
    db.session.commit()

@posts.route('/homepage/create', methods=['GET', 'POST']) #Page where user creates a new entry to be added in the database.
@login_required
def new_post():
    form= PostForm()
    if form.validate_on_submit():
        post = Post(person_met=form.name_title.data, content=form.content.data, author=current_user)
        add_to_database(post)
        flash('Log has been saved!', 'success')
        return redirect(url_for('main.homepage'))
    return render_template("create_post.html", form=form)


@posts.route('/homepage/<int:post_id>') #Route for a specific post
@login_required
def log(post_id):
    post = Post.query.get_or_404(post_id)
    if check_author_access(post):
        pass
    else: 
        return render_template('log.html', title=post.person_met, post=post)


@posts.route("/homepage/<int:post_id>/update", methods=['GET', 'POST']) #Route to modify a post
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id) #Make sure the post exists
    check_author_access(post)
    form = PostForm()
    if form.validate_on_submit(): #When the button is click, retreive the new information and update the database
        update_database(post, form)
        flash('Your post has been updated!', 'success')
        return redirect(url_for('main.homepage', post_id=post.id))
    elif request.method == 'GET': #If not fill in the text fields with the information from the database
        fill_text_fields(post, form)
    return render_template('create_post.html', title='Update Post',
                           form=form)

    
@posts.route("/homepage/<int:post_id>/delete", methods=['POST']) #Route to delete the posts
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    check_author_access(post)
    delete_in_database(post)
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('main.homepage')) #After giving user feedback, redirect to homepage.

socialtracking/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from socialtracking import db, bcrypt
from socialtracking.models import User, Post
from socialtracking.users.forms import RegistrationForm, LoginForm
from socialtracking.users.middleware import loggedIn_middleware

users = Blueprint('users', __name__)

def hash_password(form):
    return bcrypt.generate_password_hash(form.password.data).decode('utf-8')

def commit_fields_to_database(form, hashed_password):
        user = User(username=form.username.data, password=hashed_password) 
        db.session.add(user)
        db.session.commit()

def is_a_user(user, form):
    if user and bcrypt.check_password_hash(user.password, form.password.data):
        login_user(user, remember=form.remember.data)
        return True


@users.route('/', methods=['GET', 'POST'])
@loggedIn_middleware
def home():                                     #First thing user sees AKA home, but also acts like the login page to site.
    form = LoginForm()
    
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if is_a_user(user, form):
            return redirect(url_for('main.homepage'))
        else:
            flash('Login unsuccessful. Check your username and password', 'danger')
    
    return render_template('home.html', form=form)

@users.route('/register', methods=['GET', 'POST']) #Users can register for an account
@loggedIn_middleware
def register():
    form = RegistrationForm()
    
    if form.validate_on_submit():
        hashed_password = hash_password(form)
        commit_fields_to_database(form, hashed_password)
        flash('The account has been created, you may now log in', 'success')
        return redirect(url_for('main.homepage'))  
    
    return render_template('register.html', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('users.home'))

socialtracking/templates/create_post.html
{% extends "layout.html" %}

{% block content %}

  <h1>Create Post</h1>
    <form method="POST" action="">
      {{ form.hidden_tag() }}
      <fieldset>
        <legend class="border-bottom mb-4">{{ legend }}</legend>
        <div>
          {{ form.name_title.label(class="form-control-label") }} <!-- Create form using the forms classes, this displays the text discription --> 
          {{ form.name_title(class="form-control form-control-lg") }} <!-- Code for the actual text input field -->
        </div>
        <div>
          {{ form.content.label(class="form-control-label") }}
          {{ form.content(class="form-control form-control-lg") }}
        </div>
      </fieldset>
      <br>
      <div>
        {{ form.submit(class="btn btn-outline-info")}}
      </div>
    </form>
{% endblock content %}
  

socialtracking/templates/home.html
{% extends "layout.html" %}

{% block content %}
<h1>Corona Virus Impact Reduction App</h1>

<div class="left">  
  <article>
    <h2>The Project</h2>
    <p>This is the project created for the foundations to software engineering learning unit. The aim is to provide a platform fo users to be able to easily add entries to
       record the people that they have met in the past. Simply create and account and log in. Once logged in the user can add a entry/tracker. Back to the homepage, users can easily
        see all of the records and search for a specific ones. It was created using python, html, and css. Implementing Flask and SQLAlchemy aswell.
    </p>
  </article>
</div>

<div class="right">
  <div class="content-section">
  <form method="POST" action="">
    {{ form.hidden_tag() }}
    <fieldset class="form-group">
      <div class="form-group">
        {{ form.username.label(class="form-control-label") }}

        {% if form.username.errors %}
          {{ form.username(class="form-control form-control-lg is-invalid") }}
          <div class="invalid-feedback">
            {% for error in form.username.errors %}
              <span>{{ error }}</span>
          </div>
            {% endfor %}
        {% else %}
          {{ form.username(class="form-control form-control-lg") }}
        {% endif %}
      </div>
      <div class="form-group">
        {{ form.password.label(class="form-control-label") }}
          
        {% if form.password.errors %}
          {{ form.password(class="form-control form-control-lg is-invalid") }}
          <div class="invalid-feedback">
            {% for error in form.password.errors %}
              <span>{{ error }}</span>
          </div>
            {% endfor %}
        {% else %}
          {{ form.password(class="form-control form-control-lg") }}
        {% endif %}
      </div>

      <div>
        {{ form.remember() }}
        {{ form.remember.label(class="form-check-label") }}
      </div>
    </fieldset>

    <div class="form-group">
      {{ form.submit(class="btn btn-outline-info")}}
    </div>
  </form>
</div>

</div>

<div></div>

{% endblock content %}

socialtracking/templates/homepage.html
{% extends "layout.html" %}<!-- Inherit from the layout.html file -->

{% block content %}
    <h1>Home page</h1>
    <br>
    <form method="POST" class= "form-inline row justify-content-end" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group mb-2">
    
          <div>
            {{ form.search_field() }}
          </div>
        </fieldset>
    
        <div class="form-group mx-sm-3 mb-2">
          {{ form.submit(class="btn btn-outline-info")}} <!-- Getting the information from the forms and adding it to html -->
        </div>
      </form>

    <br>
    <div class="logs">
        {% for post in posts.items %} <!-- Iterating through all of the posts -->
            <article class="media content-section">
                <div class="media-body"> 
                    <div class="article-metadata">
                        <h2 class="mr-2"><a href="{{ url_for('posts.log', post_id = post.id) }}">{{ post.person_met }}</a></h2> <!-- Printing the information of each post into the html -->
                    </div>
                    
                    <p class="article-title"> <b>Details: </b> {{ post.content }}</p>
                    <p class="article-contents"><b>Date: </b> {{ post.date_met.strftime('%Y-%m-%d') }}<p>
                </div>
            </article>

        {% endfor %}

    </div>

    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %} <!-- Creating the page links at the bottom of the page -->
      {% if page_num %}
        {% if posts.page == page_num %} <!-- Different CSS for the page that we are on -->
        <a class="btn btn-info mb-4" href="{{ url_for('main.homepage', page=page_num) }}">{{ page_num }}</a>
        {% else%}
          <a class="btn btn-outline-info mb-4" href="{{ url_for('main.homepage', page=page_num) }}">{{ page_num }}</a> <!-- Create button for each page link -->
        {% endif %}
      {% else %}
      {% endif %}
    {% endfor %}

{% endblock content %}

socialtracking/templates/layout.html
<!doctype html> <!-- This is the layout and template used by all html files -->

<html lang="en">
<head>                      <!-- CSS from bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <title>Social Tracking</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style.css') }}">
</head>

<body>
    <header>

    <div class="navbody">
    <div class="navcon">
        <div class="logo">
            <h2>Social Tracking</h2>
        </div>
        
        <nav>
            <ul>
                {% if current_user.is_authenticated %} <!-- Check if user is logged in, if logged in show options to create entries and logout -->
                    <li><a href="{{ url_for('posts.new_post') }}">Create Log</a></li>
                    <li><a href="{{ url_for('users.logout') }}">Logout</a></li>
                {% else %} <!-- If not logged in show option to register -->
                <li><a href="{{ url_for('users.register') }}">Register</a></li>
                {% endif %}

            </ul>
        </nav>

    </div>

    </div>
    
</header>
<br>
    <div class="container">
    {% with messages = get_flashed_messages(with_categories=true) %} <!-- Display formating of the flashed messages -->
        {% if messages %}
            {% for category, message in messages %}
                <div class="alert alert-{{ category }}"> <!-- Use category as the bootstrap class to show if its an error or info message -->
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
    {% endwith %}
    <br>
    {% block content %}{% endblock %} <!-- Open block content so other html pages can inherit from it and simply add on to this code -->
    </div>  

    <!-- Javescript for bootstrap -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>

socialtracking/templates/log.html
{% extends "layout.html" %}

{% block content %}

<h1>Specific Tracker</h1>
{% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        {% for category, message in messages %}
            <div>
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
{% endwith %}

    <article class="media content-section">
        <div class="media-body"> 

            <div class="form-group row">
                <div class="col-sm-2 col-form-label">
                <a href=""> {{ post.author.username }} </a>
                <small>{{ post.date_met.strftime('%Y-%m-%d') }}</small>
                </div>
                {% if post.author == current_user %}
                    <div class="col-sm-10">
                        <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.update_post', post_id = post.id) }}">Update</a>
                        <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
                    </div>
                {% endif %}
            </div>
            <p class="article-contents"><b>Met with: </b> {{ post.person_met }}<p></p>
            <p class="article-title"> <b>Details: </b> {{ post.content }}</p>
            
        </div>
    </article>

    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="deleteModalLabel">Delete Entry?</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <form action="{{ url_for('posts.delete_post', post_id = post.id) }}" method="POST">
                  <input type="submit" class="btn btn-danger" value="Delete">
              </form>
            </div>
          </div>
        </div>
      </div>

{% endblock content %}

socialtracking/templates/register.html
{% extends "layout.html" %}

{% block content %}

<h1>Register</h1>
<br>
<div>
  <div class="content-section">
    <form method="POST" action="">
      {{ form.hidden_tag() }}
      <fieldset class="form-group">
        <div class="form-group">
          {{ form.username.label(class="form-control-label") }}

          {% if form.username.errors %}
            {{ form.username(class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.username.errors %}
                <span>{{ error }}</span>
            </div>
              {% endfor %}
          {% else %}
            {{ form.username(class="form-control form-control-lg") }}
          {% endif %}
        </div>
        <div class="form-group">
          {{ form.password.label(class="form-control-label") }}
          
          {% if form.password.errors %}
            {{ form.password(class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.password.errors %}
                <span>{{ error }}</span>
            </div>
              {% endfor %}
          {% else %}
            {{ form.password(class="form-control form-control-lg") }}
          {% endif %}
        </div>

        <div>
          {{ form.passwordconfirm.label(class="form-control-label") }}
          
          {% if form.passwordconfirm.errors %}
            {{ form.passwordconfirm(class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.passwordconfirm.errors %}
                <span>{{ error }}</span>
            </div>
              {% endfor %}
          {% else %}
            {{ form.passwordconfirm(class="form-control form-control-lg") }}
          {% endif %}
        </div>
      </fieldset>
  
      <div class="form-group">
        {{ form.submit(class="btn btn-outline-info")}}
      </div>
    </form>
    <div class="broder-top pt-3">
      <small class="text-muted">Already have an account? <a class="ml-2" href="{{ url_for('users.home') }}">Log In</a></small>
    </div>
  </div>
{% endblock content %}